'use client'

import { Button } from '@/components/ui/button'
import { DataTable } from '@/components/ui/data-table'
import { ColumnDef } from '@tanstack/react-table'
import {
   CheckIcon,
   ClockIcon,
   DownloadCloudIcon,
   EyeIcon,
   XIcon,
} from 'lucide-react'
import Link from 'next/link'


interface ReportsTableProps {
   data: ReportColumn[]
}

export const ReportsTable: React.FC<ReportsTableProps> = ({ data }) => {
   return <DataTable searchKey="title" columns={reportColumns} data={data} />
}

export type ReportStatus = 'completed' | 'pending' | 'failed'

export type ReportColumn = {
   id: string
   title: string
   createdAt: string // ISO date
   generatedBy: string
   rows: number
   sizeKb?: number
   status: ReportStatus
}

export const reportColumns: ColumnDef<ReportColumn>[] = [
   {
      accessorKey: 'title',
      header: 'Title',
   },
   {
      accessorKey: 'createdAt',
      header: 'Created',
      cell: (props) => {
         const value = props.getValue() as string
         return new Date(value).toLocaleString()
      },
   },
   {
      accessorKey: 'generatedBy',
      header: 'Generated By',
   },
   {
      accessorKey: 'rows',
      header: 'Rows',
   },
   {
      accessorKey: 'sizeKb',
      header: 'Size (KB)',
      cell: (props) => {
         const v = props.getValue() as number | undefined
         return v == null ? '-' : v.toLocaleString()
      },
   },
   {
      accessorKey: 'status',
      header: 'Status',
      cell: (props) => {
         const status = props.getValue() as ReportStatus
         if (status === 'completed')
            return <CheckIcon className="text-green-600" />
         if (status === 'pending')
            return <ClockIcon className="text-yellow-600" />
         return <XIcon className="text-red-600" />
      },
   },
   {
      id: 'actions',
      cell: ({ row }) => {
         const id = row.original.id
         return (
            <div className="flex items-center space-x-2">
               <Link href={`/reports/${id}`}>
                  <Button
                     size="icon"
                     variant="outline"
                     aria-label="View report"
                  >
                     <EyeIcon className="h-4" />
                  </Button>
               </Link>
               <a href={`/api/reports/${id}/download`} download>
                  <Button
                     size="icon"
                     variant="outline"
                     aria-label="Download report"
                  >
                     <DownloadCloudIcon className="h-4" />
                  </Button>
               </a>
            </div>
         )
      },
   },
]
